apiVersion: v1
kind: Service
metadata:
  labels:
    service: hangman
  name: hangman
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      port: 80
      targetPort: 3000
  selector:
    service: hangman
